services:
  traefik:
    image: traefik:v3.6.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/letsencrypt
    command:
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=brandonkamga237@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    networks:
      - web

  portfolio:
    image: brandonkamga237/myporfolio:latest  # ‚Üê Utiliser l'image au lieu de build
    container_name: myporfolio
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`brandonkamga237.griote.org`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=le"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    networks:
      - web

volumes:
  traefik-data:

networks:
  web:
    driver: bridge