version: "3.9"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx_letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy

  frontend:
    image: brandonkamga237/myporfolio:latest
    container_name: react_frontend
    restart: always
    environment:
      - VIRTUAL_HOST=brandonkamga.griote.org
      - LETSENCRYPT_HOST=brandonkamga.griote.org
      - LETSENCRYPT_EMAIL=brandonkamga237@gmail.com

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  acme:
